### ISSUE TITLE
Set map center from anchor link

### ISSUE THREAD

**Issue by sashachabin** [ekaterinburgdev/design-map#35]
When opening a design code object by anchor link, center the map on it

https://map.ekaterinburg.design/#dom-i-fotograficheskij-muzej-v-l-metenkova-dae61abf

![image](https://user-images.githubusercontent.com/22644149/205480830-f5b47b73-5f78-45d5-9a71-fb1f35217485.png)

**Comment by circus2271** [comment]
maybe this code has bad naming
